FROM public.ecr.aws/lambda/nodejs:22 AS builder
WORKDIR /usr/app
COPY ./ ./
RUN npm install
RUN npm run build
COPY ./package*.json ./dist/
ENV npm_config_ignore_scripts=true
RUN cd dist && npm install --omit=dev
 
FROM public.ecr.aws/lambda/nodejs:22
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=builder /usr/app/dist/* ./
CMD ["index.handler"]
